<a href="https://colab.research.google.com/github/defrgtyuiomp0/4iselni_metodi_progtamuvanya/blob/main/Lypetsky.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Створіть одновимірний масив (вектор) зі зростаючою геометричною прогресією, де кожне наступне число більше попереднього в 2 рази, починаючи з 2, та виведіть його значення.

In [ ]:

n = 10

arr = [2 * (2**i) for i in range(n)]

print("Масив геометричної прогресії:")
print(arr)

Масив геометричної прогресії:
[2, 4, 8, 16, 32, 64, 128, 256, 512, 1024]


Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його оберненими значеннями натуральних чисел, починаючи з 1, та виведіть його значення.


In [ ]:

rows = 3
cols = 3

matrix = [[1 / (i * cols + j + 1) for j in range(cols)] for i in range(rows)]

print("Матриця з оберненими значеннями натуральних чисел:")
for row in matrix:
    print(row)


Матриця з оберненими значеннями натуральних чисел:
[1.0, 0.5, 0.3333333333333333]
[0.25, 0.2, 0.16666666666666666]
[0.14285714285714285, 0.125, 0.1111111111111111]


Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від -3 до 3 та знайдіть максимальний елемент.


In [ ]:
import random

rows = 3
cols = 3

matrix = [[random.uniform(-3, 3) for j in range(cols)] for i in range(rows)]

print("Матриця з випадковими числами:")
for row in matrix:
    print(row)

max_element = max(max(row) for row in matrix)
print("\nМаксимальний елемент матриці:", max_element)


Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного стовпця, менших за 0.5.


In [ ]:
import random
rows = 3
cols = 3
matrix = [[random.random() for j in range(cols)] for i in range(rows)]

print("Матриця 3x3:")
for row in matrix:
    print(row)

column_sums = []
for j in range(cols):
    sum_col = sum(matrix[i][j] for i in range(rows) if matrix[i][j] < 0.5)
    column_sums.append(sum_col)

print("\nВектор-стовпчик (сума елементів < 0.5 по стовпцях):")
for value in column_sums:
    print(value)


Матриця 3x3:
[0.41499496491201626, 0.9556027718143922, 0.20342484501530855]
[0.42188853840430296, 0.4047365862633019, 0.4947923311760021]
[0.03713582193726894, 0.9557603405942566, 0.6692434034750028]

Вектор-стовпчик (сума елементів < 0.5 по стовпцях):
0.8740193252535882
0.4047365862633019
0.6982171761913106


Створіть два одновимірних масиви розміром 6, заповніть їх випадковими дійсними числами від -2 до 2 та виконайте на них поелементні операції додавання, віднімання та множення.


In [ ]:
import random

n = 6
array1 = [random.uniform(-2, 2) for _ in range(n)]
array2 = [random.uniform(-2, 2) for _ in range(n)]

print("Масив 1:", array1)
print("Масив 2:", array2)

addition = [array1[i] + array2[i] for i in range(n)]
subtraction = [array1[i] - array2[i] for i in range(n)]
multiplication = [array1[i] * array2[i] for i in range(n)]

print("\nДодавання поелементне:", addition)
print("Віднімання поелементне:", subtraction)
print("Множення поелементне:", multiplication)


Масив 1: [1.6064968657740915, -1.5070474018777578, -1.6267560242837504, 0.6753476141034294, 1.8424089184309524, 0.41893504692682715]
Масив 2: [-0.7656092421389493, 1.2579647039818824, 1.7756998307077465, 0.37244719626670664, -0.34728309149526204, -1.8856168786366516]

Додавання поелементне: [0.8408876236351421, -0.24908269789587534, 0.14894380642399607, 1.047794810370136, 1.4951258269356904, -1.4666818317098245]
Віднімання поелементне: [2.3721061079130408, -2.76501210585964, -3.402455854991497, 0.3029004178367227, 2.1896920099262145, 2.3045519255634788]
Множення поелементне: [-1.2299488479038996, -1.8958124387898185, -2.8886303969234626, 0.25153132537823203, -0.6398374649911432, -0.789950995537663]


Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1	до 5 та знайдіть їх добуток.


In [ ]:
import random

rows, cols = 4, 4

matrix1 = [[random.randint(1, 5) for j in range(cols)] for i in range(rows)]
matrix2 = [[random.randint(1, 5) for j in range(cols)] for i in range(rows)]

print("Матриця 1:")
for row in matrix1:
    print(row)

print("\nМатриця 2:")
for row in matrix2:
    print(row)

product = [[0 for j in range(cols)] for i in range(rows)]
for i in range(rows):
    for j in range(cols):
        for k in range(cols):
            product[i][j] += matrix1[i][k] * matrix2[k][j]

print("\nДобуток матриць:")
for row in product:
    print(row)


Матриця 1:
[5, 3, 4, 4]
[4, 5, 3, 4]
[2, 2, 1, 2]
[3, 1, 5, 5]

Матриця 2:
[2, 3, 4, 1]
[4, 1, 1, 2]
[4, 4, 1, 1]
[2, 5, 3, 1]

Добуток матриць:
[46, 54, 39, 19]
[48, 49, 36, 21]
[20, 22, 17, 9]
[40, 55, 33, 15]


Створіть дві матриці розміром 3x2 та 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 8 та перемножте їх між собою.


In [ ]:
import random

matrix1 = [[random.randint(1, 8) for j in range(2)] for i in range(3)]
matrix2 = [[random.randint(1, 8) for j in range(2)] for i in range(2)]

print("Матриця 1:")
for row in matrix1:
    print(row)

print("\nМатриця 2:")
for row in matrix2:
    print(row)

product = [[0 for j in range(2)] for i in range(3)]
for i in range(3):
    for j in range(2):
        for k in range(2):
            product[i][j] += matrix1[i][k] * matrix2[k][j]

print("\nДобуток матриць:")
for row in product:
    print(row)


Матриця 1:
[6, 8]
[2, 4]
[5, 5]

Матриця 2:
[6, 8]
[6, 3]

Добуток матриць:
[84, 72]
[36, 28]
[60, 55]


Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 15 та знайдіть її обернену матрицю.

In [ ]:
import random

matrix = [[random.randint(1, 15) for j in range(2)] for i in range(2)]

print("Матриця 2x2:")
for row in matrix:
    print(row)

det = matrix[0][0]*matrix[1][1] - matrix[0][1]*matrix[1][0]

if det != 0:
    inverse = [[matrix[1][1]/det, -matrix[0][1]/det],
               [-matrix[1][0]/det, matrix[0][0]/det]]
    print("\nОбернена матриця:")
    for row in inverse:
        print(row)
else:
    print("\nМатриця не має оберненої, визначник = 0")


Матриця 2x2:
[2, 7]
[11, 4]

Обернена матриця:
[-0.057971014492753624, 0.10144927536231885]
[0.15942028985507245, -0.028985507246376812]


Створіть матрицю розміром 7x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.


In [ ]:
import random

matrix = [[random.random() for j in range(3)] for i in range(7)]

print("Матриця 7x3:")
for row in matrix:
    print(row)

transposed = [[matrix[i][j] for i in range(7)] for j in range(3)]

print("\nТранспонована матриця 3x7:")
for row in transposed:
    print(row)


Матриця 7x3:
[0.3376852050954864, 0.5936192477591586, 0.7976166200389995]
[0.8198315470348781, 0.8160831694893849, 0.1794787282810354]
[0.32102147201296716, 0.8195701547427365, 0.5350352761410935]
[0.8871758528171267, 0.3224540851870482, 0.4250003860574909]
[0.04500054519858454, 0.16967296829682643, 0.8153143051958505]
[0.3294812183559065, 0.12663495325270757, 0.1435249791584935]
[0.31662366239672846, 0.8526082123023521, 0.6789252132000206]

Транспонована матриця 3x7:
[0.3376852050954864, 0.8198315470348781, 0.32102147201296716, 0.8871758528171267, 0.04500054519858454, 0.3294812183559065, 0.31662366239672846]
[0.5936192477591586, 0.8160831694893849, 0.8195701547427365, 0.3224540851870482, 0.16967296829682643, 0.12663495325270757, 0.8526082123023521]
[0.7976166200389995, 0.1794787282810354, 0.5350352761410935, 0.4250003860574909, 0.8153143051958505, 0.1435249791584935, 0.6789252132000206]


Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.


In [ ]:
import numpy as np

# матриця 3x4 з випадкових цілих чисел [1, 10]
A = np.random.randint(1, 11, size=(3, 4))

# вектор 4x1 з випадкових дійсних чисел [0, 1)
b = np.random.rand(4, 1)

# множення матриці на вектор
result = A @ b   # або np.dot(A, b)

print("Матриця A (3x4):\n", A)
print("\nВектор b (4x1):\n", b)
print("\nРезультат добутку (3x1):\n", result)


Матриця A (3x4):
 [[ 4  2  3  6]
 [ 9 10 10  6]
 [ 5  1  9  9]]

Вектор b (4x1):
 [[0.43432694]
 [0.29927598]
 [0.49894756]
 [0.04024656]]

Результат добутку (3x1):
 [[ 4.07418177]
 [12.1326572 ]
 [ 7.3236578 ]]


Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.


In [ ]:
import numpy as np

# матриця 2x3 з випадкових дійсних чисел [0,1)
A = np.random.rand(2, 3)

# вектор 3x1 з випадкових дійсних чисел [0,1)
b = np.random.rand(3, 1)

# добуток матриці на вектор
result = A @ b   # або np.dot(A, b)

print("Матриця A (2x3):\n", A)
print("\nВектор b (3x1):\n", b)
print("\nРезультат (2x1):\n", result)


Матриця A (2x3):
 [[0.8688249  0.69307973 0.71675328]
 [0.29130679 0.39050969 0.77357996]]

Вектор b (3x1):
 [[0.1978778 ]
 [0.72845278]
 [0.71998448]]

Результат (2x1):
 [[1.19284825]
 [0.89907658]]


Створіть дві матриці розміром 6x6, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню суму.


In [ ]:
import numpy as np

# створюємо дві матриці 6x6
A = np.random.randint(1, 11, size=(6, 6))
B = np.random.randint(1, 11, size=(6, 6))

# сума матриць
C = A + B

print("Матриця A:\n", A)
print("\nМатриця B:\n", B)
print("\nСума матриць A + B:\n", C)


Матриця A:
 [[ 2 10  6  7  5  2]
 [ 8 10 10  2  5  3]
 [ 2  1  4  5  1  3]
 [10  8  5  1  9  3]
 [10  1  7  8 10  3]
 [ 2 10  3  8  1  4]]

Матриця B:
 [[ 3  4  8  1  2  2]
 [ 3  5  3  2  1  5]
 [ 5  2  1  4  9  9]
 [ 7  1  7  2  6  7]
 [ 5  4 10  9  7  8]
 [10  7  3  3  1  9]]

Сума матриць A + B:
 [[ 5 14 14  8  7  4]
 [11 15 13  4  6  8]
 [ 7  3  5  9 10 12]
 [17  9 12  3 15 10]
 [15  5 17 17 17 11]
 [12 17  6 11  2 13]]


Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть добуток їх елементів.


In [ ]:
import numpy as np

# дві матриці 3x3 з випадкових дійсних чисел [0,1)
A = np.random.rand(3, 3)
B = np.random.rand(3, 3)

# покомпонентний добуток
C = A * B   # або np.multiply(A, B)

print("Матриця A:\n", A)
print("\nМатриця B:\n", B)
print("\nДобуток елементів (A * B):\n", C)


Матриця A:
 [[0.70621392 0.62583373 0.56072884]
 [0.41730968 0.316824   0.56953883]
 [0.36496078 0.4505251  0.29518048]]

Матриця B:
 [[0.78396442 0.29619008 0.56655891]
 [0.13359073 0.31001196 0.94091786]
 [0.70627262 0.53397887 0.8551246 ]]

Добуток елементів (A * B):
 [[0.55364658 0.18536574 0.31768592]
 [0.0557487  0.09821923 0.53588926]
 [0.25776181 0.24057089 0.25241609]]


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -5 до 5 та знайдіть суму елементів матриці, які більше за їх середнє арифметичне значення.


In [ ]:
import numpy as np

# матриця 3x3 з випадкових дійсних чисел у [-5, 5]
A = np.random.uniform(-5, 5, size=(3, 3))

# середнє арифметичне
mean_val = np.mean(A)

# елементи, більші за середнє
greater_elements = A[A > mean_val]

# їх сума
result = np.sum(greater_elements)

print("Матриця A:\n", A)
print("\nСереднє арифметичне:", mean_val)
print("\nЕлементи більші за середнє:\n", greater_elements)
print("\nСума цих елементів:", result)


Матриця A:
 [[-4.7292703  -4.14666468 -0.90818013]
 [-3.3631242  -0.79138954  0.3082406 ]
 [-3.29910356  1.43296614 -4.24401178]]

Середнє арифметичне: -2.19339304958056

Елементи більші за середнє:
 [-0.90818013 -0.79138954  0.3082406   1.43296614]

Сума цих елементів: 0.041637071315845375


Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найменше ціле значення в кожному рядку матриці.


In [ ]:
import numpy as np

# матриця 3x3 з випадкових дійсних чисел [0,1)
A = np.random.rand(3, 3)

# мінімальні значення в кожному рядку
row_min = np.min(A, axis=1)

# беремо цілі частини
row_min_int = np.floor(row_min).astype(int)

# робимо вектор-стовпчик
vector_col = row_min_int.reshape(-1, 1)

print("Матриця A:\n", A)
print("\nМінімальні значення по рядках:", row_min)
print("\nЦілі частини мінімальних значень:", row_min_int)
print("\nВектор-стовпчик:\n", vector_col)


Матриця A:
 [[0.67111047 0.94278588 0.32769883]
 [0.10183995 0.01807877 0.47152937]
 [0.36533918 0.88381054 0.21188606]]

Мінімальні значення по рядках: [0.32769883 0.01807877 0.21188606]

Цілі частини мінімальних значень: [0 0 0]

Вектор-стовпчик:
 [[0]
 [0]
 [0]]
